[tool.ruff]
fix=true
line-length=120
select=["ALL"]
ignore=["D1","D203","D213","FA102","I","ANN001", "Q000", "DJ001","RUF003", "N807", "DJ008", "ANN101"]

extend-select = ["C4", "SIM", "TCH"]
show-fixes = true
target-version = "py37"


[tool.ruff.extend-per-file-ignores]
"tests/*.py"=["S101", "S311"]

[tool.ruff.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 5